### ISSUE TITLE
problem with downloading datase: SyntaxError:  (repo_commit_hash=) 

### ISSUE THREAD

**Issue by co1one** [allenai/objaverse-xl#24]
Thanks for the amazing work! But i have a problem when downloading the dataset:
<img width="502" alt="image" src="https://github.com/allenai/objaverse-xl/assets/74175280/7913c8d8-d602-4767-a394-262f55b0ae90">

```
import objaverse.xl as oxl

annotations = oxl.get_annotations(
    download_dir="~/.objaverse" # default download directory
)
annotations

print(annotations)
```

when im runing this code, i encountered this error:
```
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/chaoyi/objaverse/test.py", line 2, in <module>
    import objaverse.xl as oxl
  File "/home/ubuntu/anaconda3/envs/rl/lib/python3.7/site-packages/objaverse/xl/__init__.py", line 7, in <module>
    from objaverse.xl.github import GitHubDownloader
  File "<fstring>", line 1
    (repo_commit_hash=)
                     ^
SyntaxError: invalid syntax
```

im on a ubuntu20.4

**Comment by mattdeitke** [comment]
Might need to use a newer version of Python that supports f-strings. Maybe try with Python >3.8 :)

**Comment by co1one** [comment]
May i ask again that what if i need to use a mirror huggingface , with link in the codebase i need to change? Thanks again!

**Comment by ouceduxzk** [comment]
pyhton 3.12 works, while 3.13 dont
